### ISSUE TITLE
Why did you put a license on someone's else code ?

### ISSUE THREAD

**Issue by CrimsonHere** [RipperStore/RipperStoreReuploader#1]
Why did you decide to put a license on Natiive/Skatinglasagna old project since he did make the base and most of what's in that project and you have not given him any credit.

**Comment by Sighyu** [comment]
This is old but still going to reply I worked on it together with him when rmod was still a thing he don't care about vrchat anymore. He even asked me to publicly post it online after he left vrchat

**Comment by LargestBoi** [comment]
Just wanna add its ironic to see you of all people complaining about missing credits ;-;

**Comment by CrimsonHere** [comment]
> Just wanna add it's ironic to see you of all people complaining about missing credits ;-;

Considering all the code you showcases is from other people with no credits a L on your part after all. Plz learn common c# script kitty. ;)

**Comment by LargestBoi** [comment]
> > Just wanna add it's ironic to see you of all people complaining about missing credits ;-;
> 
> Considering all the code you showcases is from other people with no credits a L on your part after all. Plz learn common c# script kitty. ;)

Mad deflect, everything I have ever posted to my repository has been mine or I have had consent to post, you wouldn't know what that's like based on your repos tho, would you?

**Comment by CrimsonHere** [comment]
> > > Just wanna add it's ironic to see you of all people complaining about missing credits ;-;
> > 
> > 
> > Considering all the code you showcases is from other people with no credits a L on your part after all. Plz learn common c# script kitty. ;)
> 
> Mad deflect, everything I have ever posted to my repository has been mine or I have had consent to post, you wouldn't know what that's like based on your repos tho, would you?

Your only repo is a rename of someone else's code with no changes besides the name lmao.

**Comment by LargestBoi** [comment]
> > > > Just wanna add it's ironic to see you of all people complaining about missing credits ;-;
> > > 
> > > 
> > > Considering all the code you showcases is from other people with no credits a L on your part after all. Plz learn common c# script kitty. ;)
> > 
> > Mad deflect, everything I have ever posted to my repository has been mine or I have had consent to post, you wouldn't know what that's like based on your repos tho, would you?
> 
> Your only repo is a rename of someone else's code with no changes besides the name lmao. And yall legit pasted remod and changed its name to aries avatar logger lmao from what I remember wasn't requiem against people using a reuploader?

All fully credited, name was originally remod ares, name was changed after requi requested it kindly, name was changed and that was that. And it seems you are running out of points trying to use old arguments you already lost, first being unoriginal with code now with arguments? What's next?

**Comment by CrimsonHere** [comment]
> > > > > Just wanna add it's ironic to see you of all people complaining about missing credits ;-;
> > > > 
> > > > 
> > > > Considering all the code you showcases is from other people with no credits a L on your part after all. Plz learn common c# script kitty. ;)
> > > 
> > > 
> > > Mad deflect, everything I have ever posted to my repository has been mine or I have had consent to post, you wouldn't know what that's like based on your repos tho, would you?
> > 
> > 
> > Your only repo is a rename of someone else's code with no changes besides the name lmao. And yall legit pasted remod and changed its name to aries avatar logger lmao from what I remember wasn't requiem against people using a reuploader?
> 
> All fully credited, name was originally remod ares, name was changed after requi requested it kindly, name was changed and that was that. And it seems you are running out of points trying to use old arguments you already lost, first being unoriginal with code now with arguments? What's next?
> 
> I am also finna stop replying from here on out cause ripper store reuploaders GitHub honesty ain't the place, you won't change I won't so eh no point to it in the end.

Maybe 1 day you will actually learn a language make somthing for yourself instead on riding others for clout. When that happends you will gain my respect until then I recommend knee pads ;)

**Comment by lenoobwastaken** [comment]
HOLY SHIT GUYS MY BALLS ITCH LIKE REALLY BAD PLEASE HELP

**Comment by lenoobwastaken** [comment]
@CrimsonHere @LargestBoi can you please scratched them

**Comment by Sighyu** [comment]
> > Just wanna add it's ironic to see you of all people complaining about missing credits ;-;
> 
> Considering all the code you showcases is from other people with no credits a L on your part after all. Plz learn common c# script kitty. ;)

explains why most of the stuff I make shows up in other peoples client :)

closing this as this issue is useless

**Comment by CrimsonHere** [comment]
> > > Just wanna add it's ironic to see you of all people complaining about missing credits ;-;
> > 
> > 
> > Considering all the code you showcases is from other people with no credits a L on your part after all. Plz learn common c# script kitty. ;)
> 
> explains why most of the stuff I make shows up in other peoples client :)
> 
> closing this as this issue is useless

That was a response to largest do you know how to read ?

**Comment by LargestBoi** [comment]
mans closed the issue, drop it

**Comment by CrimsonHere** [comment]
> mans closed the issue, drop it

Na but you started in and he jump in the middle lmao can you fight your own battles or you gonna wear them knee pads out?

**Comment by LargestBoi** [comment]
As I told you there is no point, arguing with a useless excuse of a human being like you gets nobody anywhere. You will leave sucking your own dick, to your tiny ass community who is only there cause they are povo and are there to use "your" leaks and cracks. You won't change, refuse to accept anything that doesn't fit you looking like some macho man and have everybody else’s dicks down your throat how you can't stop talking bout them. You bring nothing of value, anywhere your repos are entirely rip offs, leaks, cracks and there is a reason your name carries no respect, an actual clown is who I have more respect for at least they trying to get people to laugh at em, you do is as your fucking passive. You have tried multiple times to DDOS our servers after I hurt your feelings and aren't able to fucking do shit, cloud flare has prevented every single one of your shitty attacks because at the end of the day you are harmless. Have no place in this or any community honestly, one of the very few I have found to somehow be mutually hated across the board you absolute ape. Okay, now I am done.

**Comment by CrimsonHere** [comment]
> As I told you there is no point, arguing with a useless excuse of a human being like you gets nobody anywhere. You will leave sucking your own dick, to your tiny ass community who is only there cause they are povo and are there to use "your" leaks and cracks. You won't change, refuse to accept anything that doesn't fit you looking like some macho man and have everybody else’s dicks down your throat how you can't stop talking bout them. You bring nothing of value, anywhere your repos are entirely rip offs, leaks, cracks and there is a reason your name carries no respect, an actual clown is who I have more respect for at least they trying to get people to laugh at em, you do is as your fucking passive. You have tried multiple times to DDOS our servers after I hurt your feelings and aren't able to fucking do shit, cloud flare has prevented every single one of your shitty attacks because at the end of the day you are harmless. Have no place in this or any community honestly, one of the very few I have found to somehow be mutually hated across the board you absolute ape. Okay, now I am done.

I haven't  done any ddosing so don't  know where u got that idea but you have zero friends 3 of your personal friend have talked shit abt you publicly lmao. You have no repos besides umbras spoof renamed you don't even have a beginner understanding of c# or you would know better. Yes I do make cracks because there are people that run around starting bs for clout aka you or they have been selling github code like many of your friends. And speaking of sucking dick that's all you do. You even payed for outher people to fix open source code for the avi logger because you again don't know any c#. Are you gonna 1 pay someone to respond for you or 2 suck someones dick again to fight for you ?

**Comment by LargestBoi** [comment]
XD wow man that's crazy how you gotta reach so far up your ass to pull out bullshit like that. But I guess that's all you do, talk out of your ass because your scared your fragile ego will break down in front of your adooooring fans. Take one step back and look at the bigger picture there is a reason you are where you are and I am where I am. How much shit have you been banned from at this point man like come on? Take the hint. As much as I want to keep this going some of us have better shit to do so I'll leave it here. We won't get anywhere so for the last time drop it, I know you prob Gon reply to this with some more BS and when I don't reply think you got some hazaaa amazing win. And honestly I don't care because I have somthing amazing, a life away from this shit. I put this phone down and go out to a dinner or maybe go with some mates to the movies. I can rest happy no matter what you reply and that's somthing time and time again you have proven you can't do. So I'll throw ya a bone and stop replying, taking this "win" go on and earn all those little internet points your brain got addicted to. And maybe one day you will be smart enough to look back and think. Fuck I was dumb, and that's okay, we all been stupid at some point, it's if you can change that matters man.

**Comment by CrimsonHere** [comment]
> XD wow man that's crazy how you gotta reach so far up your ass to pull out bullshit like that. But I guess that's all you do, talk out of your ass because your scared your fragile ego will break down in front of your adooooring fans. Take one step back and look at the bigger picture there is a reason you are where you are and I am where I am. How much shit have you been banned from at this point man like come on? Take the hint. As much as I want to keep this going some of us have better shit to do so I'll leave it here. We won't get anywhere so for the last time drop it, I know you prob Gon reply to this with some more BS and when I don't reply think you got some hazaaa amazing win. And honestly I don't care because I have somthing amazing, a life away from this shit. I put this phone down and go out to a dinner or maybe go with some mates to the movies. I can rest happy no matter what you reply and that's somthing time and time again you have proven you can't do. So I'll throw ya a bone and stop replying, taking this "win" go on and earn all those little internet points your brain got addicted to. And maybe one day you will be smart enough to look back and think. Fuck I was dumb, and that's okay, we all been stupid at some point, it's if you can change that matters man.
> 
> EDIT: also yee this kinda does make both of us look like asshats, I shouldn't be getting heated over random internet shit but eh, everyone has room for improvement at the end of the day

I'm enjoying my self here don't know abt you but unixian was payed to make yalls avi logger for yalls bv4 paste lmao
